### ISSUE TITLE
建议把底部版权信息里的“由Hexo强力驱动”关掉

### ISSUE THREAD

**Issue by code004Accepted** [CJTracer/CJTracer.github.io#1]
在_config.yml里修改~
（PS:我是cbj，好像我也在用hexo-next-gemini做博客。。。）
code004.ml
code004accepted.github.io

**Comment by CJTracer** [comment]
没必要啊

**Comment by code004Accepted** [comment]
点错了qwq

**Comment by code004Accepted** [comment]
...

**Comment by leverimmy** [comment]
> 在_config.yml里修改~
> （PS:我是cbj，好像我也在用hexo-next-gemini做博客。。。）
> code004.ml
> code004accepted.github.io

Hexo 这个地方有版权吧……必须要保留。

建议仔细看一下 LICENSE？

**Comment by code004Accepted** [comment]
看过，只有NexT主题要求（
Hexo没有要求

> c) A covered work must retain «NexT» official website link (https://theme-next.org) in footer section of every website created, modified or manipulated by using «NexT». «NexT» theme configuration must be:

> footer:
>   theme:
>     enable: true
> Collaborators, best contributors and all authors specified in the 'docs/AUTHORS.md' file of «NexT» repository under the 'https://github.com/theme-next' organization can ignore theme info link requirements.

**Comment by leverimmy** [comment]
（说错了（
